apiVersion: v1
kind: Service
metadata:
  name: airbyte-backup-service
  namespace: airbyte-backup
spec:
  selector:
    app.kubernetes.io/name: cost-analyzer
  ports:
  - port: 9090
    targetPort: 9090