resource_name: New DEV DB I2I Test
definition_type: source
definition_id: 435bb9a5-7887-4809-aa58-28c27df0d7ad
definition_image: airbyte/source-mysql
definition_version: 1.0.21
configuration:
  ssl: true
  host: localhost
  port: 3306
  database: envDev
  password: '**********'
  ssl_mode:
    mode: preferred
  username: devi-ideas2it
  tunnel_method:
    ssh_key: '**********'
    tunnel_host: 18.218.52.238
    tunnel_port: 22
    tunnel_user: forge
    tunnel_method: SSH_KEY_AUTH
  replication_method:
    method: STANDARD
