resource_name: DH Dev
definition_type: source
definition_id: decd338e-5647-4c0b-adf4-da0e75f5a750
definition_image: airbyte/source-postgres
definition_version: 1.0.42
configuration:
  ssl: false
  host: digital-human.czlebpbzjy34.us-east-2.rds.amazonaws.com
  port: 5432
  schemas:
  - public
  database: qxt-digitalhuman
  password: '**********'
  ssl_mode:
    mode: disable
  username: cube_svc
  tunnel_method:
    tunnel_method: NO_TUNNEL
  replication_method:
    method: Standard
