resource_name: AUTH Integration Engine DEV
definition_type: destination
definition_id: 424892c4-daac-4491-b35d-c6688ba547ba
definition_image: airbyte/destination-snowflake
definition_version: 0.4.47
configuration:
  host: yqb44523.us-east-1.snowflakecomputing.com
  role: IOT_DEV_ROLE
  schema: AUTH_TO_SNOWFLAKE
  database: IOT_DEV_DATABASE
  username: IOT_DEV
  warehouse: IOT_DEV_WAREHOUSE
  credentials:
    password: '**********'
  loading_method:
    method: Standard
