resource_name: newco_prod_ro
definition_type: source
definition_id: 435bb9a5-7887-4809-aa58-28c27df0d7ad
definition_image: airbyte/source-mysql
definition_version: 1.0.21
configuration:
  ssl: true
  host: newco-prod-readonly.czlebpbzjy34.us-east-2.rds.amazonaws.com
  port: 3306
  database: forge
  password: '**********'
  ssl_mode:
    mode: preferred
  username: blueorange
  tunnel_method:
    tunnel_method: NO_TUNNEL
  replication_method:
    method: STANDARD
