resource_name: snowflake-integration-dev
definition_type: destination
definition_id: 424892c4-daac-4491-b35d-c6688ba547ba
definition_image: airbyte/destination-snowflake
definition_version: 0.4.47
configuration:
  host: yqb44523.us-east-1.snowflakecomputing.com
  role: INTEGRATION_DEV_ROLE
  schema: INTEGRATION_DEV_SCHEMA
  database: INTEGRATION_DEV_DATABASE
  username: INTEGRATION_DEV
  warehouse: INTEGRATION_DEV_WAREHOUSE
  credentials:
    password: '**********'
  loading_method:
    method: Standard
