resource_name: digitalhuman-prod-postgres-ro-replica-1.cus3uzdaukij.us-east-1.rds.amazonaws.com
definition_type: source
definition_id: decd338e-5647-4c0b-adf4-da0e75f5a750
definition_image: airbyte/source-postgres
definition_version: 1.0.42
configuration:
  ssl: false
  host: localhost
  port: 4444
  schemas:
  - public
  database: digitalhuman
  password: '**********'
  ssl_mode:
    mode: disable
  username: cbudano_bo
  tunnel_method:
    tunnel_method: NO_TUNNEL
  replication_method:
    method: Standard
