resource_name: common-dev-postgres-acct_1
definition_type: source
definition_id: decd338e-5647-4c0b-adf4-da0e75f5a750
definition_image: airbyte/source-postgres
definition_version: 1.0.42
configuration:
  ssl: false
  host: common-dev-postgres.csuzcomajhlx.us-east-1.rds.amazonaws.com
  port: 5432
  schemas: []
  database: acct_1
  password: '**********'
  ssl_mode:
    mode: disable
  username: airbyte_svc
  tunnel_method:
    tunnel_method: NO_TUNNEL
  replication_method:
    method: Standard
