resource_name: Snowflake-dhuman
definition_type: destination
definition_id: 424892c4-daac-4491-b35d-c6688ba547ba
definition_image: airbyte/destination-snowflake
definition_version: 0.4.47
configuration:
  host: yqb44523.us-east-1.snowflakecomputing.com
  role: AIRBYTE_ROLE
  schema: DHPUBLIC
  database: AIRBYTE_DATABASE
  username: AIRBYTE_QUEXT
  warehouse: AIRBYTE_WAREHOUSE
  credentials:
    password: '**********'
  loading_method:
    method: Standard
