resource_name: newco_dev
definition_type: source
definition_id: 435bb9a5-7887-4809-aa58-28c27df0d7ad
definition_image: airbyte/source-mysql
definition_version: 1.0.21
configuration:
  ssl: true
  host: 127.0.0.1
  port: 3306
  database: forge
  password: '**********'
  ssl_mode:
    mode: preferred
  username: blueorange-applications
  tunnel_method:
    ssh_key: '**********'
    tunnel_host: 18.218.52.238
    tunnel_port: 22
    tunnel_user: forge
    tunnel_method: SSH_KEY_AUTH
  replication_method:
    method: STANDARD
